add lesson2 part3 solution
StrategDZR/mera_selenium pull request #1
Opened 2020-11-01 19:08 UTC by StrategDZR

2020-11-04 17:51 UTC, VeryBadProgrammer commented
Первым делом структура
вот пример рабочей программы,которую используют в моем проекте
ресурсы пока тебе не нужны, а папка assembly -что-то ненужно(не смотри тоже на нее
получаетя, что есть две раза слова java, в тесте и мэйне, в тесте пишутся все тесты, в мэйне вспомогательные классы,вроде описания страницы
![image](https://user-images.githubusercontent.com/14930647/98150215-fc520380-1ed6-11eb-86ad-e2cb2a4950de.png)

и внутри кажной папки куча фолдеров,соотвественно

2020-11-04 18:02 UTC, VeryBadProgrammer requested changes
А пришли еще логи, что оба теста проходят,а то у меня ошибку выкидывает

2020-11-04 18:02 UTC, VeryBadProgrammer commented on src/test/java/tests/TestTask1.java
> +public class TestTask1 {
лучше слово 'Test' указывать в конце названия класса,если он для теста, тогда будет более читабельно

2020-11-04 18:02 UTC, VeryBadProgrammer commented on src/test/java/tests/TestTask2.java
> +    public void tierUp() {
обычно называют setUp

2020-11-04 18:02 UTC, VeryBadProgrammer commented on src/test/java/tests/TestTask2.java
> +    public void tierDown(){
tearDown()

2020-11-04 18:02 UTC, VeryBadProgrammer commented on src/test/java/tests/TestTask1.java
там где то внизу этого класса есть @org.junit.Test такая строка
лучше импорт делать вверху и писать @Test

2020-11-05 08:19 UTC, StrategDZR commented
> Первым делом структура
> вот пример рабочей программы,которую используют в моем проекте
> ресурсы пока тебе не нужны, а папка assembly -что-то ненужно(не смотри тоже на нее
> получаетя, что есть две раза слова java, в тесте и мэйне, в тесте пишутся все тесты, в мэйне вспомогательные классы,вроде описания страницы
> ![image](https://user-images.githubusercontent.com/14930647/98150215-fc520380-1ed6-11eb-86ad-e2cb2a4950de.png)
> 
> и внутри кажной папки куча фолдеров,соотвественно

я отталкивался от того, что в main модуле лежит код приложения, а все тесты хранятся в модуле test

2020-11-05 13:50 UTC, StrategDZR commented on src/test/java/tests/TestTask1.java
Заимпортировал

2020-11-05 13:51 UTC, StrategDZR commented on src/test/java/tests/TestTask2.java
> +    public void tierDown(){
исправлено

2020-11-05 13:52 UTC, StrategDZR commented on src/test/java/tests/TestTask2.java
> +    public void tierUp() {
исправлено

2020-11-05 13:52 UTC, StrategDZR commented on src/test/java/tests/TestTask1.java
> +public class TestTask1 {
видимо, питоновская привычка =)

2020-11-05 13:56 UTC, StrategDZR commented
```
Testing started at 16:54 ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 1318
Only local connections are allowed.
[1604584481.156][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 05, 2020 4:54:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 8270
Only local connections are allowed.
[1604584493.194][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 05, 2020 4:54:55 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 22s
2 actionable tasks: 1 executed, 1 up-to-date
16:54:58: Task execution finished ':test --tests *'.

```

![image](https://user-images.githubusercontent.com/15121709/98249924-e3555b00-1f87-11eb-86c7-7be958e56305.png)

2020-11-07 10:31 UTC, VeryBadProgrammer approved these changes

2020-11-07 13:52 UTC, merged