Lesson 8: add cart test
StrategDZR/mera_selenium pull request #10
Opened 2020-12-03 12:13 UTC by StrategDZR

/*
Задание 13. Сделайте сценарий работы с корзиной
Сделайте сценарий для добавления товаров в корзину и удаления товаров из корзины.

1) открыть главную страницу
2) открыть первый товар из списка
2) добавить его в корзину (при этом может случайно добавиться товар, который там уже есть, ничего страшного)
3) подождать, пока счётчик товаров в корзине обновится
4) вернуться на главную страницу, повторить предыдущие шаги ещё два раза,
чтобы в общей сложности в корзине было 3 единицы товара
5) открыть корзину (в правом верхнем углу кликнуть по ссылке Checkout)
6) удалить все товары из корзины один за другим, после каждого удаления подождать, пока внизу обновится таблица
 */

Logs:
```

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 16025
Only local connections are allowed.
[1606997178.742][WARNING]: Timed out connecting to Chrome, retrying...
дек. 03, 2020 3:06:20 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Trying to set Medium Size
[Test worker] INFO pages.AbstractPage - Clicking on Add to Cart button
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Trying to set Medium Size
[Test worker] INFO pages.AbstractPage - Clicking on Add to Cart button
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Trying to set Medium Size
[Test worker] INFO pages.AbstractPage - Clicking on Add to Cart button
[Test worker] INFO pages.AbstractPage - Opening Checkout page
[Test worker] INFO pages.AbstractPage - Deleting all products in the cart
No shortcuts found
BUILD SUCCESSFUL in 38s
2 actionable tasks: 2 executed
15:06:50: Task execution finished ':test --tests "cases.CartTest"'.

```

2020-12-03 16:21 UTC, VeryBadProgrammer requested changes

2020-12-03 16:21 UTC, VeryBadProgrammer commented on src/test/java/pages/ShopCartPage.java
> +        try {
Что за обработчик,зачем он нужен?

2020-12-03 16:21 UTC, VeryBadProgrammer commented on src/test/java/pages/ShopProductPage.java
> +        try {
и тут

2020-12-03 16:21 UTC, VeryBadProgrammer commented on src/test/java/cases/CartTest.java
> +        cartPage.deleteAllProducts();
ты же знаешь,что тебе надо удалить qtyOfProducts товаров, может проще как то это использовтаь?

2020-12-03 18:43 UTC, StrategDZR commented on src/test/java/pages/ShopCartPage.java
> +        try {
Когда в корзине находится несколько разных товаров, по умолчанию блок продукта с кнопкой Remove "крутятся" в карусельной анимации.
Чтобы не потерять элемент кнопки, можно нажать на "shortcut" (после нажатия анимация перестаёт работать).
Однако, этот шорткат есть только тогда, когда в корзине несколько разных продуктов, что происходит не всегда.
Поэтому шорткат может быть, а может не быть.

2020-12-03 18:44 UTC, StrategDZR commented on src/test/java/cases/CartTest.java
> +        cartPage.deleteAllProducts();
в том случае, если в корзине будет три одинаковых продукта, то кнопка Remove будет только одна.

2020-12-03 18:46 UTC, StrategDZR commented on src/test/java/pages/ShopProductPage.java
> +        try {
Не у всех продуктов есть параметр "Size". У тех, у которых есть, он обязательный.
По заданию нужно брать первый товар на главной странице, а он каждый раз разный.

2020-12-07 15:43 UTC, VeryBadProgrammer approved these changes

2020-12-08 05:09 UTC, merged