Lesson 8: external links test
StrategDZR/mera_selenium pull request #11
Opened 2020-12-04 07:33 UTC by StrategDZR

Задание 14. Проверьте, что ссылки открываются в новом окне
Сделайте сценарий, который проверяет, что ссылки на странице редактирования страны открываются в новом окне.

Сценарий должен состоять из следующих частей:

1) зайти в админку
2) открыть пункт меню Countries (или страницу http://localhost/litecart/admin/?app=countries&doc=countries)
3) открыть на редактирование какую-нибудь страну или начать создание новой
4) возле некоторых полей есть ссылки с иконкой в виде квадратика со стрелкой -- они ведут на внешние страницы
и открываются в новом окне, именно это и нужно проверить.

Конечно, можно просто убедиться в том, что у ссылки есть атрибут target="_blank".
Но в этом упражнении требуется именно кликнуть по ссылке, чтобы она открылась в новом окне,
потом переключиться в новое окно, закрыть его, вернуться обратно, и повторить эти действия для всех таких ссылок.

Не забудьте, что новое окно открывается не мгновенно, поэтому требуется ожидание открытия окна.

Logs:
```

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 40832
Only local connections are allowed.
[1607067079.452][WARNING]: Timed out connecting to Chrome, retrying...
дек. 04, 2020 10:31:21 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Opening the URL as admin: http://localhost/litecart/admin/?app=countries&doc=countries
[Test worker] INFO pages.AbstractPage - Clicking on Add New Country button
[Test worker] INFO pages.AbstractPage - Getting all external links
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
[Test worker] INFO pages.AbstractPage - Checking if the second tab opened
[Test worker] INFO pages.AbstractPage - Closing second tab
BUILD SUCCESSFUL in 11s
2 actionable tasks: 2 executed
10:31:25: Task execution finished ':test --tests "cases.ExternalLinksTest"'.

```

2020-12-07 15:45 UTC, VeryBadProgrammer requested changes

2020-12-07 15:45 UTC, VeryBadProgrammer commented on src/test/java/pages/AddNewCountryPage.java
> +    private final String uniquePageElementLoc = "//h1[contains(., \" Add New Country\")]";
Почему используешь точку,а не конкретный аттрибут?

2020-12-08 05:22 UTC, StrategDZR commented on src/test/java/pages/AddNewCountryPage.java
> +    private final String uniquePageElementLoc = "//h1[contains(., \" Add New Country\")]";
Привык использовать как шорткат для text(). 
Здесь можно и contains() убрать, в принципе.

//h1[text()=" Add New Country"]

2020-12-08 15:09 UTC, VeryBadProgrammer commented on src/test/java/cases/ExternalLinksTest.java
> +    @After
по аннотации почитай,какие еще бывают,что бы понимать

2020-12-08 15:09 UTC, VeryBadProgrammer approved these changes

2020-12-08 17:04 UTC, StrategDZR commented on src/test/java/cases/ExternalLinksTest.java
> +    @After
хорошо

2020-12-08 17:04 UTC, merged