Lesson4 search ui elements: admin menu
StrategDZR/mera_selenium pull request #4
Opened 2020-11-09 14:22 UTC by StrategDZR

Logs:

![image](https://user-images.githubusercontent.com/15121709/98552909-195c4d00-22b0-11eb-929f-54f5c1a5b397.png)

```
Testing started at 17:17 ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 3645
Only local connections are allowed.
[1604931484.446][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 09, 2020 5:18:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Appearence")]
[Test worker] INFO pages.MenuPage - Check if Template is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Template")]
[Test worker] INFO pages.MenuPage - Check if Template h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Logotype")]
[Test worker] INFO pages.MenuPage - Check if Logotype h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Catalog")]
[Test worker] INFO pages.MenuPage - Check if Manufacturers is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-catalog"]//span[contains(., "Catalog")]
[Test worker] INFO pages.MenuPage - Check if Catalog h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Product Groups")]
[Test worker] INFO pages.MenuPage - Check if Product Groups h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Option Groups")]
[Test worker] INFO pages.MenuPage - Check if Option Groups h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Manufacturers")]
[Test worker] INFO pages.MenuPage - Check if Manufacturers h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Suppliers")]
[Test worker] INFO pages.MenuPage - Check if Suppliers h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Delivery Statuses")]
[Test worker] INFO pages.MenuPage - Check if Delivery Statuses h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Sold Out Statuses")]
[Test worker] INFO pages.MenuPage - Check if Sold Out Statuses h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Quantity Units")]
[Test worker] INFO pages.MenuPage - Check if Quantity Units h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"CSV Import/Export")]
[Test worker] INFO pages.MenuPage - Check if CSV Import/Export h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Countries")]
[Test worker] INFO pages.MenuPage - Check if Countries h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Currencies")]
[Test worker] INFO pages.MenuPage - Check if Currencies h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Customers")]
[Test worker] INFO pages.MenuPage - Check if Newsletter is displayed
[Test worker] INFO pages.MenuPage - Try to click in //ul[@class="docs"]//span[contains(., "Customers")]
[Test worker] INFO pages.MenuPage - Check if Customers h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"CSV Import/Export")]
[Test worker] INFO pages.MenuPage - Check if CSV Import/Export h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Newsletter")]
[Test worker] INFO pages.MenuPage - Check if Newsletter h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Geo Zones")]
[Test worker] INFO pages.MenuPage - Check if Geo Zones h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Languages")]
[Test worker] INFO pages.MenuPage - Check if Storage Encoding is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-languages"]//span[contains(., "Languages")]
[Test worker] INFO pages.MenuPage - Check if Languages h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Storage Encoding")]
[Test worker] INFO pages.MenuPage - Check if Storage Encoding h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Modules")]
[Test worker] INFO pages.MenuPage - Check if Payment is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-customer"]//span[contains(., "Customer")]
[Test worker] INFO pages.MenuPage - Check if Customer Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Shipping")]
[Test worker] INFO pages.MenuPage - Check if Shipping Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Payment")]
[Test worker] INFO pages.MenuPage - Check if Payment Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Order Total")]
[Test worker] INFO pages.MenuPage - Check if Order Total Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Order Success")]
[Test worker] INFO pages.MenuPage - Check if Order Success Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Order Action")]
[Test worker] INFO pages.MenuPage - Check if Order Action Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Background Jobs")]
[Test worker] INFO pages.MenuPage - Check if Job Modules h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Orders")]
[Test worker] INFO pages.MenuPage - Check if Order Statuses is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-orders"]//span[contains(., "Orders")]
[Test worker] INFO pages.MenuPage - Check if Orders h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Order Statuses")]
[Test worker] INFO pages.MenuPage - Check if Order Statuses h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Pages")]
[Test worker] INFO pages.MenuPage - Check if Pages h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Reports")]
[Test worker] INFO pages.MenuPage - Check if Most Sold Products is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Monthly Sales")]
[Test worker] INFO pages.MenuPage - Check if Monthly Sales h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Most Sold Products")]
[Test worker] INFO pages.MenuPage - Check if Most Sold Products h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Most Shopping Customers")]
[Test worker] INFO pages.MenuPage - Check if Most Shopping Customers h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Settings")]
[Test worker] INFO pages.MenuPage - Check if Images is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Store Info")]
[Test worker] INFO pages.MenuPage - Check if Settings h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Defaults")]
[Test worker] INFO pages.MenuPage - Check if Settings h1 element is displayed
[Test worker] INFO pages.MenuPage - Try to click in / [...]

2020-11-10 17:54 UTC, VeryBadProgrammer requested changes

2020-11-10 17:54 UTC, VeryBadProgrammer commented on src/test/java/pages/MenuPage.java
> +    }
выглядят как два одинаковых метода, может стоит скрестить их в один?

2020-11-10 17:54 UTC, VeryBadProgrammer commented on src/test/java/pages/MenuPage.java
> +    public String vqmodsSubMenuItem = "//li[@id=\"doc-vqmods\"]//span[contains(., \"vQmods\")]";
Все переменные внутри класса для старинцы должны быть private. Чтобы соблюдалась секьюрити и ООП

Выглядать как оиднаковые элементы, есть идеи,как код можно улучшить?

2020-11-10 17:54 UTC, VeryBadProgrammer commented on src/test/java/cases/AdminMenuTest.java
> +        menuPage.clickOnMenuItem(menuPage.templateSubMenuItem);
очень странная запись. то есть ты идешь в menuPage, находишь там templateSubMenuItem, сохраняешь это, затем снова идешь в menuPage, находишь метод clickOnMenuItem и передаешь ему то самое сохраненное значение.
Попробуй все это оптимизировать. Пиши идеи в глипе, чтобы несколько раз не переделывать)

2020-11-10 20:29 UTC, StrategDZR commented on src/test/java/pages/MenuPage.java
> +    public String vqmodsSubMenuItem = "//li[@id=\"doc-vqmods\"]//span[contains(., \"vQmods\")]";
Создать два родительских класса: один для MenuItem,  другой для SubmenuItem.
Локатор склеивать из шаблона и текста, который будет передаваться в параметрах.

2020-11-10 20:32 UTC, StrategDZR commented on src/test/java/pages/MenuPage.java
> +    }
Думаю, можно создать базовый метод типа "checkElementIsDisplayed()", использовать его в этих двух функциях.
Хочу, чтобы именно <h1> локатор искался.

2020-11-10 20:35 UTC, StrategDZR commented on src/test/java/cases/AdminMenuTest.java
> +        menuPage.clickOnMenuItem(menuPage.templateSubMenuItem);
Тут я закладывал следующий смысл:
menuPage.clickOnMenuItem(menuPage.appearenceMenuItem); - кликаем в верхнеуровневое меню.
menuPage.checkSubMenuIsDisplayed("Template"); - проверяем, что верхнеуровневое меню открылось.
menuPage.clickOnMenuItem(menuPage.templateSubMenuItem); - кликаем в меню второго уровня, чтобы проверить наличие h1 элемента.

2020-11-10 20:37 UTC, StrategDZR commented on src/test/java/pages/MenuPage.java
> +    public String vqmodsSubMenuItem = "//li[@id=\"doc-vqmods\"]//span[contains(., \"vQmods\")]";
> Все переменные внутри класса для старинцы должны быть private. Чтобы соблюдалась секьюрити и ООП
Ох, то есть, кроме толпы локаторов еще будет и толпа геттеров?

2020-11-11 18:36 UTC, VeryBadProgrammer commented on src/test/java/pages/MenuPage.java
> +    }
хороший план

2020-11-11 18:37 UTC, VeryBadProgrammer commented on src/test/java/cases/AdminMenuTest.java
> +        menuPage.clickOnMenuItem(menuPage.templateSubMenuItem);
тут можно очень сильно сократить код в классе, добавивт кое что, и используя цикл

2020-11-11 18:38 UTC, VeryBadProgrammer commented on src/test/java/pages/MenuPage.java
> +    public String vqmodsSubMenuItem = "//li[@id=\"doc-vqmods\"]//span[contains(., \"vQmods\")]";
геттеров можно будет избежать, если придумаешь как обойти такое большое количетсво однотипных переменных

2020-11-11 18:38 UTC, VeryBadProgrammer commented on src/test/java/pages/MenuPage.java
> +    public String vqmodsSubMenuItem = "//li[@id=\"doc-vqmods\"]//span[contains(., \"vQmods\")]";
> Создать два родительских класса: один для MenuItem, другой для SubmenuItem.
> Локатор склеивать из шаблона и текста, который будет передаваться в параметрах.

да,вот что-то подобное, но не обязательно создавать два разных класса

2020-11-11 18:56 UTC, StrategDZR commented on src/test/java/cases/AdminMenuTest.java
> +        menuPage.clickOnMenuItem(menuPage.templateSubMenuItem);
приходит в голову типизировать подход к проверке одного MenuItem, который и можно будет прогнать циклом по листу, состоящему из пунктов меню

2020-11-13 12:06 UTC, StrategDZR commented
Logs:

```
Testing started at 14:58 ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 31859
Only local connections are allowed.
[1605268708.491][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 13, 2020 2:58:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Appearence")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-template"]//span[contains(., "Template")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Template text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-logotype"]//span[contains(., "Logotype")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Logotype text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Catalog")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-catalog"]//span[contains(., "Catalog")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Catalog text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-product_groups"]//span[contains(., "Product Groups")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Product Groups text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-option_groups"]//span[contains(., "Option Groups")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Option Groups text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-manufacturers"]//span[contains(., "Manufacturers")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Manufacturers text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-suppliers"]//span[contains(., "Suppliers")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Suppliers text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-delivery_statuses"]//span[contains(., "Delivery Statuses")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Delivery Statuses text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-sold_out_statuses"]//span[contains(., "Sold Out Statuses")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Sold Out Statuses text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-quantity_units"]//span[contains(., "Quantity Unit")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Quantity Units text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-csv"]//span[contains(., "CSV Import/Export")]
[Test worker] INFO pages.MenuPage - Check if h1 element with CSV Import/Export text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Countries")]
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Currencies")]
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Customers")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-customers"]//span[contains(., "Customers")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Customers text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-csv"]//span[contains(., "CSV Import/Export")]
[Test worker] INFO pages.MenuPage - Check if h1 element with CSV Import/Export text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-newsletter"]//span[contains(., "Newsletter")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Newsletter text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Geo Zones")]
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Languages")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-languages"]//span[contains(., "Languages")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Languages text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-storage_encoding"]//span[contains(., "Storage Encoding")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Storage Encoding text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Modules")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-customer"]//span[contains(., "Customer")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Customer Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-shipping"]//span[contains(., "Shipping")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Shipping Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-payment"]//span[contains(., "Payment")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Payment Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-order_total"]//span[contains(., "Order Total")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Order Total Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-order_success"]//span[contains(., "Order Success")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Order Success Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-order_action"]//span[contains(., "Order Action")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Order Action Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-jobs"]//span[contains(., "Background Jobs")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Job Modules text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Orders")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-orders"]//span[contains(., "Orders")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Orders text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-order_statuses"]//span[contains(., "Order Statuses")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Order Statuses text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Pages")]
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Reports")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-monthly_sales"]//span[contains(., "Monthly Sales")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Monthly Sales text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-most_sold_products"]//span[contains(., "Most Sold Products")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Most Sold Products text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-most_shopping_customers"]//span[contains(., "Most Shopping Customers")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Most Shopping Customers text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //span[contains(text(),"Settings")]
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-store_info"]//span[contains(., "Store Info")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Settings text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-defaults"]//span[contains(., "Defaults")]
[Test worker] INFO pages.MenuPage - Check if h1 element with Settings text is displayed
[Test worker] INFO pages.MenuPage - Try to click in //li[@id="doc-general"]//span[contains(., "General")]
[Test worker] INFO pages.MenuPage - Check if [...]

2020-11-13 14:34 UTC, VeryBadProgrammer approved these changes

2020-11-13 14:34 UTC, VeryBadProgrammer commented on src/test/java/pages/MenuPage.java
> +    public enum ListOfMenuItems {
ыорде уже выглядит поменьше
в идеале выносить enum в отдельный класс, но не буду тебя тут мучать уже, просто учти на будущее

2020-11-13 14:34 UTC, VeryBadProgrammer commented on src/test/java/cases/AdminMenuTest.java
> +        for (MenuPage.ListOfMenuItems menuItem : menuItems) {
Для практики, попробуй здесь использовать стримы, как только получится,можешь мержить)

2020-11-13 15:58 UTC, StrategDZR commented on src/test/java/pages/MenuPage.java
> +    public enum ListOfMenuItems {
да я тоже долго думал по этому поводу. решил, что этот енам относится к MenuPage непосредственно, поэтому и оставил внутри

2020-11-14 09:46 UTC, StrategDZR commented on src/test/java/cases/AdminMenuTest.java
> +        for (MenuPage.ListOfMenuItems menuItem : menuItems) {
вроде ничего фильтровать/мапить/коллектить не нужно, заменил на forEach с лямбдой

2020-11-14 09:46 UTC, merged