Lesson5, task 9: countries&geozones sorting
StrategDZR/mera_selenium pull request #6
Opened 2020-11-21 16:50 UTC by StrategDZR

Сделайте сценарии, которые проверяют сортировку стран и геозон (штатов) в учебном приложении litecart.

1) на странице http://localhost/litecart/admin/?app=countries&doc=countries
а) проверить, что страны расположены в алфавитном порядке
б) для тех стран, у которых количество зон отлично от нуля -- открыть страницу этой страны и там проверить, что зоны расположены в алфавитном порядке

2) на странице http://localhost/litecart/admin/?app=geo_zones&doc=geo_zones
зайти в каждую из стран и проверить, что зоны расположены в алфавитном порядке

Logs:

```
Testing started at 19:45 ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 46350
Only local connections are allowed.
[1605977146.170][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 21, 2020 7:45:48 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AdminCountriesPage - Getting list of countries
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Test worker] INFO pages.AdminCountriesPage - Getting quantity of zones
[Te [...]

2020-11-21 16:52 UTC, StrategDZR commented
Здесь вопрос появился, почему тесты не запускаются по порядку расположения?
![image](https://user-images.githubusercontent.com/15121709/99882635-0ee86e80-2c33-11eb-8721-1ed228f8eb42.png)

2020-11-23 17:27 UTC, VeryBadProgrammer commented
> Здесь вопрос появился, почему тесты не запускаются по порядку расположения?
> ![image](https://user-images.githubusercontent.com/15121709/99882635-0ee86e80-2c33-11eb-8721-1ed228f8eb42.png)

не углублялась в порядок, знаю,что точно может не по порядку работать, зависит от всяких xml и тд
при запуске всех тестов должно быть в алфавитном порядке, но как то у тебя не отображается так,может я путаю что-тою самое главное это то, что не обязательно будет порядок,в котором написано

https://testng.org/doc/documentation-main.html#running-testng
вот тут есть подробно,можешь почитать, если интересно

2020-11-23 17:45 UTC, VeryBadProgrammer requested changes

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        wait.until(ExpectedConditions.elementToBeClickable(By.xpath(loginPage.loginButton)));
Закинь все ожидалки в конструктор или в новый метод для ожидания на страницу

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        adminGeoZonesPage = new AdminGeoZonesPage(driver);
создавать экземплер объекта лучше тогда, когда он уже есть. То есть ты загружаешь браузер, затем инициализиурешь страницу, ждешь внутри конструктора,что она прогрузится и работаешь с ней

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        wait = new WebDriverWait(driver, 10);
Так же у тебя много повторяющегося кода, если не зочешь писать это постоянно, то создай AbstractTest, от которого будешь наследовать все будущие тесты( предыдущие не меняй, много работы) и закинь туда setUp, который будет создавать драйвер, может даже открывать браузер, если захочешь

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/pages/AdminCountriesPage.java
> +    private final String findCountryByNameElement = "//td/a[contains(., \"%s\")]";
не очень понятно,что будет искать локатор

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        wait.until(ExpectedConditions.elementToBeClickable(By.xpath(loginPage.loginButton)));
и логин тоже

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        adminCountriesPage.checkAlphabeticalOrderOfList(geoZones);
вот тут не понятно, почему у тебя разные страницы в тесте, хотя ты вроде никуда не кликал или getGeoZonesList отображается на обхей странице?

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/pages/AdminCountriesPage.java
> +        Assert.assertEquals(initialListOfNames, sortedListOfNames);
верни тут булен, чтобы фейлы по проверке все были в тесте

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/pages/AdminCountriesPage.java
> +        driver.findElement(By.xpath(locator)).click();
driver.$(By.xpath(locator)).waitUntil(.....).click(); две строчки можно одной заменить вроде( не помню,работает это с WebElement, с Selenide Element точно работает

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/pages/AdminCountriesPage.java
> +    public List<WebElement> getList(String locator) {
Возвращаешь лист чего, лучше отобразить в названии метода это, чтобы было понятно

2020-11-23 17:45 UTC, VeryBadProgrammer commented on src/test/java/pages/AdminGeoZonesPage.java
> +public class AdminGeoZonesPage extends AdminCountriesPage {
объясни мне связь, это страница внутри другой или как они зависимы?

2020-11-23 18:58 UTC, StrategDZR commented on src/test/java/pages/AdminGeoZonesPage.java
> +public class AdminGeoZonesPage extends AdminCountriesPage {
Это две разных страницы, но очень друг на друга похожих.
Чтобы не делать копипасту я занаследовался

2020-11-23 18:59 UTC, StrategDZR commented on src/test/java/pages/AdminCountriesPage.java
> +    public List<WebElement> getList(String locator) {
здесь внутренняя функция, надо сделать её приватной. Используется в получении списка зон и стран

2020-11-23 19:02 UTC, VeryBadProgrammer commented on src/test/java/pages/AdminGeoZonesPage.java
> +public class AdminGeoZonesPage extends AdminCountriesPage {
если страницы похожи, лучше сделать для них шаблбон какой нибудь в виде абстрактного класса, просто по коду ощещение,что одна внутри другой, а это вообще быть не может
внутри страницы могут быть панельки то есть какая то часть страницы, но не другие страницы

2020-11-23 19:05 UTC, StrategDZR commented on src/test/java/pages/AdminCountriesPage.java
> +        driver.findElement(By.xpath(locator)).click();
на чистом селениуме не нашёл такой возможности

2020-11-23 19:10 UTC, StrategDZR commented on src/test/java/pages/AdminCountriesPage.java
> +        Assert.assertEquals(initialListOfNames, sortedListOfNames);
Сделано, теперь ассерт в самих тестах

2020-11-23 19:11 UTC, StrategDZR commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        adminCountriesPage.checkAlphabeticalOrderOfList(geoZones);
нет, это ошибка, исправил.

2020-11-23 19:13 UTC, StrategDZR commented on src/test/java/pages/AdminCountriesPage.java
> +    private final String findCountryByNameElement = "//td/a[contains(., \"%s\")]";
добавил имя формы в xpath

2020-11-23 19:28 UTC, StrategDZR commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        wait = new WebDriverWait(driver, 10);
Добавил AbstractTest

2020-11-23 19:29 UTC, StrategDZR commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        wait.until(ExpectedConditions.elementToBeClickable(By.xpath(loginPage.loginButton)));
в AbstractPage добавил openPageAndLoginAsAdmin()

2020-11-23 19:36 UTC, StrategDZR commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        adminGeoZonesPage = new AdminGeoZonesPage(driver);
То есть, внутри теста я сделал setUp(), где создал и запустил браузер, а в самих тестах уже инициализировать страницы с подтверждением загрузки в конструкторе самой страницы?

2020-11-23 19:47 UTC, StrategDZR commented on src/test/java/pages/AdminGeoZonesPage.java
> +public class AdminGeoZonesPage extends AdminCountriesPage {
Уберу наследование, чтобы сделать ожидание в конструкторе

2020-11-23 20:01 UTC, StrategDZR commented on src/test/java/pages/AdminGeoZonesPage.java
> +public class AdminGeoZonesPage extends AdminCountriesPage {
В итоге создал AbstractPage.

2020-11-23 20:10 UTC, StrategDZR commented on src/test/java/pages/AdminCountriesPage.java
> +    public List<WebElement> getList(String locator) {
вынес в AbstractPage

2020-11-24 13:31 UTC, VeryBadProgrammer commented on src/test/java/cases/SortingCountriesAndGeozonesTest.java
> +        adminGeoZonesPage = new AdminGeoZonesPage(driver);
ты норм сделал
есть два варинат,либо прогрузку в конструкторе юзать, либо после инициализации метод прогрузки вызывать. Это универсальное, в некоторых случаях оба работает нормально,в некоторых какой то один

2020-11-24 13:32 UTC, VeryBadProgrammer approved these changes

2020-11-24 17:39 UTC, merged