Lesson5 check ui of product page
StrategDZR/mera_selenium pull request #7
Opened 2020-11-25 15:37 UTC by StrategDZR

Задание 10. Проверить, что открывается правильная страница товара

Сделайте сценарий, который проверяет, что при клике на товар открывается правильная страница товара в учебном приложении litecart.

Более точно, нужно открыть главную страницу, выбрать первый товар в блоке Campaigns и проверить следующее:

а) на главной странице и на странице товара совпадает текст названия товара
б) на главной странице и на странице товара совпадают цены (обычная и акционная)
в) обычная цена зачёркнутая и серая (можно считать, что "серый" цвет это такой, у которого в RGBa представлении
одинаковые значения для каналов R, G и B)
г) акционная жирная и красная (можно считать, что "красный" цвет это такой, у которого в RGBa представлении
каналы G и B имеют нулевые значения)
(цвета надо проверить на каждой странице независимо, при этом цвета на разных страницах могут не совпадать)
д) акционная цена крупнее, чем обычная (это тоже надо проверить на каждой странице независимо)

Logs:

```
Testing started at 18:35 ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 12457
Only local connections are allowed.
[1606318520.594][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 25, 2020 6:35:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Getting product details from the main page
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Getting product details from the product page
[Test worker] INFO pages.AbstractPage - Checking if campaign font is bold and red
[Test worker] INFO pages.AbstractPage - Checking if text is bold
[Test worker] INFO pages.AbstractPage - Checking if color is red
[Test worker] INFO pages.AbstractPage - Checking if campaign font is bold and red
[Test worker] INFO pages.AbstractPage - Checking if text is bold
[Test worker] INFO pages.AbstractPage - Checking if color is red
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 48169
Only local connections are allowed.
[1606318530.499][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 25, 2020 6:35:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Getting product details from the main page
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Getting product details from the product page
[Test worker] INFO pages.AbstractPage - Checking price is the same
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 44679
Only local connections are allowed.
[1606318540.929][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 25, 2020 6:35:42 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Getting product details from the main page
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Getting product details from the product page
[Test worker] INFO pages.AbstractPage - Checking if regular price is strikethrough and grey
[Test worker] INFO pages.AbstractPage - Checking if text is strikethrough
[Test worker] INFO pages.AbstractPage - Checking if color is grey
[Test worker] INFO pages.AbstractPage - Checking if regular price is strikethrough and grey
[Test worker] INFO pages.AbstractPage - Checking if text is strikethrough
[Test worker] INFO pages.AbstractPage - Checking if color is grey
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 4917
Only local connections are allowed.
[1606318551.946][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 25, 2020 6:35:54 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Getting product details from the main page
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Getting product details from the product page
[Test worker] INFO pages.AbstractPage - Checking name is the same
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 22913
Only local connections are allowed.
[1606318561.929][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 25, 2020 6:36:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Getting product details from the main page
[Test worker] INFO pages.AbstractPage - Click on product with position 1
[Test worker] INFO pages.AbstractPage - Getting product details from the product page
[Test worker] INFO pages.AbstractPage - Checking campaign font is bigger than font of regular price
[Test worker] INFO pages.AbstractPage - Checking campaign font is bigger than font of regular price
BUILD SUCCESSFUL in 54s
2 actionable tasks: 2 executed
18:36:08: Task execution finished ':test --tests "cases.LayoutOfProductPageTest"'.

```

2020-11-26 14:48 UTC, VeryBadProgrammer requested changes

2020-11-26 14:48 UTC, VeryBadProgrammer commented on src/test/java/cases/AbstractTest.java
> +        if (driver != null){
зачем?

2020-11-26 14:48 UTC, VeryBadProgrammer commented on src/test/java/cases/LayoutOfProductPageTest.java
> +        mainPage.openProductPage("Campaigns", 1);
это повотряется во всех тестах?
если да, выкини это в сетап

2020-11-26 14:48 UTC, VeryBadProgrammer commented on src/test/java/cases/LayoutOfProductPageTest.java
> +                && isRegularPriceStrikethroughAndGrey(detailsFromProductPage));
лучше буловские разделять, чтобы когда выкидывалась ошибка, не нужно было рефакторить в чем конкретно проблема,а сразу отобразилось бы это в логах
то есть сделать две проверки, в иделе использоваьт функцию с собщение, которое передается вторым параметром

2020-11-26 17:58 UTC, StrategDZR commented on src/test/java/cases/AbstractTest.java
> +        if (driver != null){
хотел браузер не переоткрывать, уберу

2020-11-26 17:59 UTC, StrategDZR commented on src/test/java/cases/LayoutOfProductPageTest.java
> +        mainPage.openProductPage("Campaigns", 1);
да, был вопрос по этому, как лучше сделать. вынесу в сетап

2020-11-26 18:20 UTC, StrategDZR commented on src/test/java/cases/LayoutOfProductPageTest.java
> +                && isRegularPriceStrikethroughAndGrey(detailsFromProductPage));
а больше одного ассерта в тесте это нормально?

2020-11-28 08:39 UTC, VeryBadProgrammer commented on src/test/java/cases/LayoutOfProductPageTest.java
> +                && isRegularPriceStrikethroughAndGrey(detailsFromProductPage));
да, ты же в тесте можешь проверять все,что угодно, так что и количсевто ассертов зависит от того сколько всего надо проверять

2020-11-28 08:40 UTC, VeryBadProgrammer approved these changes

2020-11-28 12:17 UTC, VeryBadProgrammer commented on src/test/java/cases/LayoutOfProductPageTest.java
> +        super.setUp();
поищи значения в аннотации before, что-то вроде 'depends on', тогда не надо явно вызывать метод из супер класса, а то он 2 раза будет вызываться, если там есть аннотация before

2020-11-28 17:17 UTC, StrategDZR commented on src/test/java/cases/LayoutOfProductPageTest.java
> +        super.setUp();
поискал, не нашёл, в понедельник спишемся, расскажешь, как надо было

2020-11-28 17:17 UTC, merged