Lesson6 sign up test
StrategDZR/mera_selenium pull request #8
Opened 2020-11-27 12:04 UTC by StrategDZR

Сделайте сценарий для регистрации нового пользователя в учебном приложении litecart (не в админке, а в клиентской части магазина).

Сценарий должен состоять из следующих частей:

1) регистрация новой учётной записи с достаточно уникальным адресом электронной почты
(чтобы не конфликтовало с ранее созданными пользователями, в том числе при предыдущих запусках того же самого сценария),
2) выход (logout), потому что после успешной регистрации автоматически происходит вход,
3) повторный вход в только что созданную учётную запись,
4) и ещё раз выход.

В качестве страны выбирайте United States, штат произвольный. При этом формат индекса -- пять цифр.

Проверки можно никакие не делать, только действия -- заполнение полей, нажатия на кнопки и ссылки.
Если сценарий дошёл до конца, то есть созданный пользователь смог выполнить вход и выход -- значит создание прошло успешно.

Logs:
```
Testing started at 15:02 ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 30466
Only local connections are allowed.
[1606478541.164][WARNING]: Timed out connecting to Chrome, retrying...
нояб. 27, 2020 3:02:23 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[Test worker] INFO pages.AbstractPage - Click on Create Account link
[Test worker] INFO pages.AbstractPage - Start creating new account with random parameters
[Test worker] INFO pages.AbstractPage - User with the following credentials was created: patrick.jaskolski@example.com 4c65k8x3k52gx
[Test worker] INFO pages.AbstractPage - Logging out...
[Test worker] INFO pages.AbstractPage - Login from main page as patrick.jaskolski@example.com
[Test worker] INFO pages.AbstractPage - Logging out...
BUILD SUCCESSFUL in 17s
2 actionable tasks: 2 executed
15:02:34: Task execution finished ':test --tests "cases.SignUpTest"'.

```

2020-11-28 12:21 UTC, VeryBadProgrammer requested changes

2020-11-28 12:21 UTC, VeryBadProgrammer commented on src/test/java/cases/AbstractTest.java
> +        adminLoginPage.loginAsAdmin();
а предыдущие тесты не сломались?

2020-11-28 12:21 UTC, VeryBadProgrammer commented on src/test/java/cases/AbstractTest.java
> +        adminLoginPage.loginAsAdmin();
остальное посмотрю, когда смержишь с предыдущим заданием, сложно читать

2020-11-28 17:21 UTC, StrategDZR commented on src/test/java/cases/AbstractTest.java
> +        adminLoginPage.loginAsAdmin();
Предыдущие не сломались, я сразу везде переименовал.
Предыдущее смёржил

2020-11-29 11:49 UTC, VeryBadProgrammer approved these changes

2020-11-29 20:12 UTC, merged